%YAML:1.0
rgb_path: "/home/m/ws/src/ros_projects/dataset/rgb/"


good_match_threshold: 10

start_index: 200
end_index: 400

rgb_dir: "/home/m/ws/src/ros_projects/dataset/rgb/"
depth_dir: "/home/m/ws/src/ros_projects/dataset/depth/"


voxel_grid: 0.01


min_good_match: 10

min_inliers: 5

max_norm: 0.3

keyframe_threshold: 0.1
max_norm_lp: 2.0


nearby_loops: 5
random_loops: 5
